#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=5G
#SBATCH --time=2:00:00
#SBATCH -p short
#SBATCH -J grap_each_proton_traj_position

#module load python/3.6.0

#The former steps we need to cut from our SDATCAR file
needed_step=`echo 15000`
echo ${needed_step}
grep "Direct" XDATCAR > numlines
numlines=`wc -l numlines | cut -d' ' -f1`
rm numlines
rest_line=`echo ${numlines}'-'${needed_step} | bc`
echo ${rest_line}


./grap_each_proton_traj_position.sh ${rest_line} >> LOG
